# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-16815-agent-8/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xcvu095-ffvc1517-2-e

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include /home/savi/8v3shell/mig_shell/pr_region_proj/pr_region.srcs/sources_1/bd/pr_region_2/ipshared/7e3a/hdl {
      /opt/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /opt/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include /home/savi/8v3shell/mig_shell/pr_region_proj/pr_region.srcs/sources_1/bd/pr_region_2/ipshared/7e3a/hdl {
      ./.Xil/Vivado-16815-agent-8/realtime/pr_region_2_dummy1_0_0_stub.v
      ./.Xil/Vivado-16815-agent-8/realtime/pr_region_2_dummy1_1_0_stub.v
      ./.Xil/Vivado-16815-agent-8/realtime/pr_region_2_pcl_axifull_bridge_0_0_stub.v
      ./.Xil/Vivado-16815-agent-8/realtime/pr_region_2_pcl_axilite_bridge_0_0_stub.v
      ./.Xil/Vivado-16815-agent-8/realtime/pr_region_2_xbar_1_stub.v
      ./.Xil/Vivado-16815-agent-8/realtime/pr_region_2_xbar_0_stub.v
      ./.Xil/Vivado-16815-agent-8/realtime/pr_region_2_auto_us_1_stub.v
      ./.Xil/Vivado-16815-agent-8/realtime/pr_region_2_auto_us_0_stub.v
      /home/savi/8v3shell/mig_shell/pr_region_proj/pr_region.srcs/sources_1/bd/pr_region_2/hdl/pr_region_2.v
      /home/savi/8v3shell/mig_shell/pr_region_proj/pr_region.srcs/sources_1/bd/pr_region_2/hdl/pr_region_2_wrapper.v
    }
      rt::read_vhdl -lib xpm /opt/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-16815-agent-8/realtime/pr_region_2_wrapper_synth.xdc
    rt::sdcChecksum
    set rt::top pr_region_2_wrapper
    set rt::ioInsertion false
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: out_of_context
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-16815-agent-8/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
