// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// CTRL_BUS
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of input_offset
//        bit 31~0 - input_offset[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of output_offset
//        bit 31~0 - output_offset[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of batch_size
//        bit 31~0 - batch_size[31:0] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of num_inputs
//        bit 31~0 - num_inputs[31:0] (Read/Write)
// 0x2c : reserved
// 0x30 : Data signal of num_outputs
//        bit 31~0 - num_outputs[31:0] (Read/Write)
// 0x34 : reserved
// 0x38 : Data signal of enable_relu
//        bit 31~0 - enable_relu[31:0] (Read/Write)
// 0x3c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XFC_LAYER_CTRL_BUS_ADDR_AP_CTRL            0x00
#define XFC_LAYER_CTRL_BUS_ADDR_GIE                0x04
#define XFC_LAYER_CTRL_BUS_ADDR_IER                0x08
#define XFC_LAYER_CTRL_BUS_ADDR_ISR                0x0c
#define XFC_LAYER_CTRL_BUS_ADDR_INPUT_OFFSET_DATA  0x10
#define XFC_LAYER_CTRL_BUS_BITS_INPUT_OFFSET_DATA  32
#define XFC_LAYER_CTRL_BUS_ADDR_OUTPUT_OFFSET_DATA 0x18
#define XFC_LAYER_CTRL_BUS_BITS_OUTPUT_OFFSET_DATA 32
#define XFC_LAYER_CTRL_BUS_ADDR_BATCH_SIZE_DATA    0x20
#define XFC_LAYER_CTRL_BUS_BITS_BATCH_SIZE_DATA    32
#define XFC_LAYER_CTRL_BUS_ADDR_NUM_INPUTS_DATA    0x28
#define XFC_LAYER_CTRL_BUS_BITS_NUM_INPUTS_DATA    32
#define XFC_LAYER_CTRL_BUS_ADDR_NUM_OUTPUTS_DATA   0x30
#define XFC_LAYER_CTRL_BUS_BITS_NUM_OUTPUTS_DATA   32
#define XFC_LAYER_CTRL_BUS_ADDR_ENABLE_RELU_DATA   0x38
#define XFC_LAYER_CTRL_BUS_BITS_ENABLE_RELU_DATA   32

