set_property SRC_FILE_INFO {cfile:/home/savi/8v3shell/mig_shell/.Xil/Vivado-20700-agent-8/dcp131/static_region_pr_decoupler_0_0_in_context.xdc rfile:../dcp131/static_region_pr_decoupler_0_0_in_context.xdc id:1 order:EARLY scoped_inst:static_region_i/pr_decoupler_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/savi/8v3shell/mig_shell/.Xil/Vivado-20700-agent-8/dcp133/static_region_util_ds_buf_0_in_context.xdc rfile:../dcp133/static_region_util_ds_buf_0_in_context.xdc id:2 order:EARLY scoped_inst:static_region_i/util_ds_buf} [current_design]
set_property SRC_FILE_INFO {cfile:/home/savi/8v3shell/mig_shell/.Xil/Vivado-20700-agent-8/dcp135/static_region_xdma_0_0_in_context.xdc rfile:../dcp135/static_region_xdma_0_0_in_context.xdc id:3 order:EARLY scoped_inst:static_region_i/xdma_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/savi/8v3shell/mig_shell/.Xil/Vivado-20700-agent-8/dcp137/static_region_xbar_0_in_context.xdc rfile:../dcp137/static_region_xbar_0_in_context.xdc id:4 order:EARLY scoped_inst:static_region_i/xdma_0_axi_periph/xbar} [current_design]
set_property SRC_FILE_INFO {cfile:/home/savi/8v3shell/mig_shell/.Xil/Vivado-20700-agent-8/dcp139/static_region_dummy1_0_0_in_context.xdc rfile:../dcp139/static_region_dummy1_0_0_in_context.xdc id:5 order:EARLY scoped_inst:static_region_i/pr_region/dummy1_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/savi/8v3shell/mig_shell/.Xil/Vivado-20700-agent-8/dcp141/static_region_pcl_axifull_bridge_0_0_in_context.xdc rfile:../dcp141/static_region_pcl_axifull_bridge_0_0_in_context.xdc id:6 order:EARLY scoped_inst:static_region_i/pr_region/pcl_axifull_bridge_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/savi/8v3shell/mig_shell/.Xil/Vivado-20700-agent-8/dcp143/static_region_pcl_axilite_bridge_0_0_in_context.xdc rfile:../dcp143/static_region_pcl_axilite_bridge_0_0_in_context.xdc id:7 order:EARLY scoped_inst:static_region_i/pr_region/pcl_axilite_bridge_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/savi/8v3shell/mig_shell/.Xil/Vivado-20700-agent-8/dcp145/static_region_ddr4_0_0_in_context.xdc rfile:../dcp145/static_region_ddr4_0_0_in_context.xdc id:8 order:EARLY scoped_inst:static_region_i/ddr4_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/savi/8v3shell/mig_shell/.Xil/Vivado-20700-agent-8/dcp147/static_region_rst_ddr4_0_300M_0_in_context.xdc rfile:../dcp147/static_region_rst_ddr4_0_300M_0_in_context.xdc id:9 order:EARLY scoped_inst:static_region_i/rst_ddr4_0_300M} [current_design]
set_property SRC_FILE_INFO {cfile:/home/savi/8v3shell/mig_shell/.Xil/Vivado-20700-agent-8/dcp149/static_region_util_vector_logic_0_0_in_context.xdc rfile:../dcp149/static_region_util_vector_logic_0_0_in_context.xdc id:10 order:EARLY scoped_inst:static_region_i/util_vector_logic_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/savi/8v3shell/mig_shell/.Xil/Vivado-20700-agent-8/dcp151/static_region_axi_smc_1_in_context.xdc rfile:../dcp151/static_region_axi_smc_1_in_context.xdc id:11 order:EARLY scoped_inst:static_region_i/axi_smc} [current_design]
set_property SRC_FILE_INFO {cfile:/home/savi/8v3shell/mig_shell/.Xil/Vivado-20700-agent-8/dcp153/static_region_auto_cc_0_in_context.xdc rfile:../dcp153/static_region_auto_cc_0_in_context.xdc id:12 order:EARLY scoped_inst:static_region_i/xdma_0_axi_periph/s00_couplers/auto_cc} [current_design]
set_property SRC_FILE_INFO {cfile:/home/savi/8v3shell/mig_shell/.Xil/Vivado-20700-agent-8/dcp155/static_region_auto_us_0_in_context.xdc rfile:../dcp155/static_region_auto_us_0_in_context.xdc id:13 order:EARLY scoped_inst:static_region_i/pr_region/axi_interconnect_1/s00_couplers/auto_us} [current_design]
set_property SRC_FILE_INFO {cfile:/home/savi/8v3shell/mig_shell/bitstream.xdc rfile:../../../bitstream.xdc id:14} [current_design]
set_property SRC_FILE_INFO {cfile:/home/savi/8v3shell/mig_shell/ddr4sdram_locs_b0_x64.xdc rfile:../../../ddr4sdram_locs_b0_x64.xdc id:15} [current_design]
set_property SRC_FILE_INFO {cfile:/home/savi/8v3shell/mig_shell/pcie_constr.xdc rfile:../../../pcie_constr.xdc id:16} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 3.333 [get_pins static_region_i/pr_decoupler_0/aclk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells static_region_i/pr_decoupler_0]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_clk_clk_n[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_clk_clk_n[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_clk_clk_p[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_clk_clk_p[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells static_region_i/util_ds_buf]
set_property src_info {type:SCOPED_XDC file:3 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxn[0]}]
set_property src_info {type:SCOPED_XDC file:3 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxn[0]}]
set_property src_info {type:SCOPED_XDC file:3 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxn[1]}]
set_property src_info {type:SCOPED_XDC file:3 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxn[1]}]
set_property src_info {type:SCOPED_XDC file:3 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxn[2]}]
set_property src_info {type:SCOPED_XDC file:3 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxn[2]}]
set_property src_info {type:SCOPED_XDC file:3 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxn[3]}]
set_property src_info {type:SCOPED_XDC file:3 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxn[3]}]
set_property src_info {type:SCOPED_XDC file:3 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxn[4]}]
set_property src_info {type:SCOPED_XDC file:3 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxn[4]}]
set_property src_info {type:SCOPED_XDC file:3 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxn[5]}]
set_property src_info {type:SCOPED_XDC file:3 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxn[5]}]
set_property src_info {type:SCOPED_XDC file:3 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxn[6]}]
set_property src_info {type:SCOPED_XDC file:3 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxn[6]}]
set_property src_info {type:SCOPED_XDC file:3 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxn[7]}]
set_property src_info {type:SCOPED_XDC file:3 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxn[7]}]
set_property src_info {type:SCOPED_XDC file:3 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxp[0]}]
set_property src_info {type:SCOPED_XDC file:3 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxp[0]}]
set_property src_info {type:SCOPED_XDC file:3 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxp[1]}]
set_property src_info {type:SCOPED_XDC file:3 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxp[1]}]
set_property src_info {type:SCOPED_XDC file:3 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxp[2]}]
set_property src_info {type:SCOPED_XDC file:3 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxp[2]}]
set_property src_info {type:SCOPED_XDC file:3 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxp[3]}]
set_property src_info {type:SCOPED_XDC file:3 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxp[3]}]
set_property src_info {type:SCOPED_XDC file:3 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxp[4]}]
set_property src_info {type:SCOPED_XDC file:3 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxp[4]}]
set_property src_info {type:SCOPED_XDC file:3 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxp[5]}]
set_property src_info {type:SCOPED_XDC file:3 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxp[5]}]
set_property src_info {type:SCOPED_XDC file:3 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxp[6]}]
set_property src_info {type:SCOPED_XDC file:3 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxp[6]}]
set_property src_info {type:SCOPED_XDC file:3 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxp[7]}]
set_property src_info {type:SCOPED_XDC file:3 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_rxp[7]}]
set_property src_info {type:SCOPED_XDC file:3 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txn[0]}]
set_property src_info {type:SCOPED_XDC file:3 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txn[0]}]
set_property src_info {type:SCOPED_XDC file:3 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txn[1]}]
set_property src_info {type:SCOPED_XDC file:3 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txn[1]}]
set_property src_info {type:SCOPED_XDC file:3 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txn[2]}]
set_property src_info {type:SCOPED_XDC file:3 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txn[2]}]
set_property src_info {type:SCOPED_XDC file:3 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txn[3]}]
set_property src_info {type:SCOPED_XDC file:3 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txn[3]}]
set_property src_info {type:SCOPED_XDC file:3 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txn[4]}]
set_property src_info {type:SCOPED_XDC file:3 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txn[4]}]
set_property src_info {type:SCOPED_XDC file:3 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txn[5]}]
set_property src_info {type:SCOPED_XDC file:3 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txn[5]}]
set_property src_info {type:SCOPED_XDC file:3 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txn[6]}]
set_property src_info {type:SCOPED_XDC file:3 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txn[6]}]
set_property src_info {type:SCOPED_XDC file:3 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txn[7]}]
set_property src_info {type:SCOPED_XDC file:3 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txn[7]}]
set_property src_info {type:SCOPED_XDC file:3 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txp[0]}]
set_property src_info {type:SCOPED_XDC file:3 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txp[0]}]
set_property src_info {type:SCOPED_XDC file:3 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txp[1]}]
set_property src_info {type:SCOPED_XDC file:3 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txp[1]}]
set_property src_info {type:SCOPED_XDC file:3 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txp[2]}]
set_property src_info {type:SCOPED_XDC file:3 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txp[2]}]
set_property src_info {type:SCOPED_XDC file:3 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txp[3]}]
set_property src_info {type:SCOPED_XDC file:3 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txp[3]}]
set_property src_info {type:SCOPED_XDC file:3 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txp[4]}]
set_property src_info {type:SCOPED_XDC file:3 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txp[4]}]
set_property src_info {type:SCOPED_XDC file:3 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txp[5]}]
set_property src_info {type:SCOPED_XDC file:3 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txp[5]}]
set_property src_info {type:SCOPED_XDC file:3 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txp[6]}]
set_property src_info {type:SCOPED_XDC file:3 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txp[6]}]
set_property src_info {type:SCOPED_XDC file:3 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txp[7]}]
set_property src_info {type:SCOPED_XDC file:3 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {pcie_7x_mgt_rtl_txp[7]}]
set_property src_info {type:SCOPED_XDC file:3 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 4 [get_pins static_region_i/xdma_0/axi_aclk]
set_property src_info {type:SCOPED_XDC file:3 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells static_region_i/xdma_0]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 3.333 [get_pins static_region_i/xdma_0_axi_periph/xbar/aclk]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells static_region_i/xdma_0_axi_periph/xbar]
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 3.333 [get_pins static_region_i/pr_region/dummy1_0/ap_clk]
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells static_region_i/pr_region/dummy1_0]
set_property src_info {type:SCOPED_XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells static_region_i/pr_region/pcl_axifull_bridge_0]
set_property src_info {type:SCOPED_XDC file:7 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells static_region_i/pr_region/pcl_axilite_bridge_0]
set_property src_info {type:SCOPED_XDC file:8 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports c0_ddr4_act_n]
set_property src_info {type:SCOPED_XDC file:8 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports c0_ddr4_act_n]
set_property src_info {type:SCOPED_XDC file:8 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[0]}]
set_property src_info {type:SCOPED_XDC file:8 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[0]}]
set_property src_info {type:SCOPED_XDC file:8 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[10]}]
set_property src_info {type:SCOPED_XDC file:8 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[10]}]
set_property src_info {type:SCOPED_XDC file:8 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[11]}]
set_property src_info {type:SCOPED_XDC file:8 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[11]}]
set_property src_info {type:SCOPED_XDC file:8 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[12]}]
set_property src_info {type:SCOPED_XDC file:8 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[12]}]
set_property src_info {type:SCOPED_XDC file:8 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[13]}]
set_property src_info {type:SCOPED_XDC file:8 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[13]}]
set_property src_info {type:SCOPED_XDC file:8 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[14]}]
set_property src_info {type:SCOPED_XDC file:8 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[14]}]
set_property src_info {type:SCOPED_XDC file:8 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[15]}]
set_property src_info {type:SCOPED_XDC file:8 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[15]}]
set_property src_info {type:SCOPED_XDC file:8 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[16]}]
set_property src_info {type:SCOPED_XDC file:8 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[16]}]
set_property src_info {type:SCOPED_XDC file:8 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[1]}]
set_property src_info {type:SCOPED_XDC file:8 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[1]}]
set_property src_info {type:SCOPED_XDC file:8 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[2]}]
set_property src_info {type:SCOPED_XDC file:8 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[2]}]
set_property src_info {type:SCOPED_XDC file:8 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[3]}]
set_property src_info {type:SCOPED_XDC file:8 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[3]}]
set_property src_info {type:SCOPED_XDC file:8 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[4]}]
set_property src_info {type:SCOPED_XDC file:8 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[4]}]
set_property src_info {type:SCOPED_XDC file:8 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[5]}]
set_property src_info {type:SCOPED_XDC file:8 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[5]}]
set_property src_info {type:SCOPED_XDC file:8 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[6]}]
set_property src_info {type:SCOPED_XDC file:8 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[6]}]
set_property src_info {type:SCOPED_XDC file:8 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[7]}]
set_property src_info {type:SCOPED_XDC file:8 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[7]}]
set_property src_info {type:SCOPED_XDC file:8 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[8]}]
set_property src_info {type:SCOPED_XDC file:8 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[8]}]
set_property src_info {type:SCOPED_XDC file:8 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[9]}]
set_property src_info {type:SCOPED_XDC file:8 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_adr[9]}]
set_property src_info {type:SCOPED_XDC file:8 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_ba[0]}]
set_property src_info {type:SCOPED_XDC file:8 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_ba[0]}]
set_property src_info {type:SCOPED_XDC file:8 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_ba[1]}]
set_property src_info {type:SCOPED_XDC file:8 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_ba[1]}]
set_property src_info {type:SCOPED_XDC file:8 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_bg[0]}]
set_property src_info {type:SCOPED_XDC file:8 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_bg[0]}]
set_property src_info {type:SCOPED_XDC file:8 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_bg[1]}]
set_property src_info {type:SCOPED_XDC file:8 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_bg[1]}]
set_property src_info {type:SCOPED_XDC file:8 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_ck_c[0]}]
set_property src_info {type:SCOPED_XDC file:8 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_ck_c[0]}]
set_property src_info {type:SCOPED_XDC file:8 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_ck_t[0]}]
set_property src_info {type:SCOPED_XDC file:8 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_ck_t[0]}]
set_property src_info {type:SCOPED_XDC file:8 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_cke[0]}]
set_property src_info {type:SCOPED_XDC file:8 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_cke[0]}]
set_property src_info {type:SCOPED_XDC file:8 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_cs_n[0]}]
set_property src_info {type:SCOPED_XDC file:8 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_cs_n[0]}]
set_property src_info {type:SCOPED_XDC file:8 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dm_n[0]}]
set_property src_info {type:SCOPED_XDC file:8 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dm_n[0]}]
set_property src_info {type:SCOPED_XDC file:8 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dm_n[1]}]
set_property src_info {type:SCOPED_XDC file:8 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dm_n[1]}]
set_property src_info {type:SCOPED_XDC file:8 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dm_n[2]}]
set_property src_info {type:SCOPED_XDC file:8 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dm_n[2]}]
set_property src_info {type:SCOPED_XDC file:8 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dm_n[3]}]
set_property src_info {type:SCOPED_XDC file:8 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dm_n[3]}]
set_property src_info {type:SCOPED_XDC file:8 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dm_n[4]}]
set_property src_info {type:SCOPED_XDC file:8 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dm_n[4]}]
set_property src_info {type:SCOPED_XDC file:8 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dm_n[5]}]
set_property src_info {type:SCOPED_XDC file:8 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dm_n[5]}]
set_property src_info {type:SCOPED_XDC file:8 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dm_n[6]}]
set_property src_info {type:SCOPED_XDC file:8 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dm_n[6]}]
set_property src_info {type:SCOPED_XDC file:8 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dm_n[7]}]
set_property src_info {type:SCOPED_XDC file:8 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dm_n[7]}]
set_property src_info {type:SCOPED_XDC file:8 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[0]}]
set_property src_info {type:SCOPED_XDC file:8 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[0]}]
set_property src_info {type:SCOPED_XDC file:8 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[10]}]
set_property src_info {type:SCOPED_XDC file:8 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[10]}]
set_property src_info {type:SCOPED_XDC file:8 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[11]}]
set_property src_info {type:SCOPED_XDC file:8 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[11]}]
set_property src_info {type:SCOPED_XDC file:8 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[12]}]
set_property src_info {type:SCOPED_XDC file:8 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[12]}]
set_property src_info {type:SCOPED_XDC file:8 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[13]}]
set_property src_info {type:SCOPED_XDC file:8 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[13]}]
set_property src_info {type:SCOPED_XDC file:8 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[14]}]
set_property src_info {type:SCOPED_XDC file:8 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[14]}]
set_property src_info {type:SCOPED_XDC file:8 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[15]}]
set_property src_info {type:SCOPED_XDC file:8 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[15]}]
set_property src_info {type:SCOPED_XDC file:8 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[16]}]
set_property src_info {type:SCOPED_XDC file:8 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[16]}]
set_property src_info {type:SCOPED_XDC file:8 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[17]}]
set_property src_info {type:SCOPED_XDC file:8 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[17]}]
set_property src_info {type:SCOPED_XDC file:8 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[18]}]
set_property src_info {type:SCOPED_XDC file:8 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[18]}]
set_property src_info {type:SCOPED_XDC file:8 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[19]}]
set_property src_info {type:SCOPED_XDC file:8 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[19]}]
set_property src_info {type:SCOPED_XDC file:8 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[1]}]
set_property src_info {type:SCOPED_XDC file:8 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[1]}]
set_property src_info {type:SCOPED_XDC file:8 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[20]}]
set_property src_info {type:SCOPED_XDC file:8 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[20]}]
set_property src_info {type:SCOPED_XDC file:8 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[21]}]
set_property src_info {type:SCOPED_XDC file:8 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[21]}]
set_property src_info {type:SCOPED_XDC file:8 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[22]}]
set_property src_info {type:SCOPED_XDC file:8 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[22]}]
set_property src_info {type:SCOPED_XDC file:8 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[23]}]
set_property src_info {type:SCOPED_XDC file:8 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[23]}]
set_property src_info {type:SCOPED_XDC file:8 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[24]}]
set_property src_info {type:SCOPED_XDC file:8 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[24]}]
set_property src_info {type:SCOPED_XDC file:8 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[25]}]
set_property src_info {type:SCOPED_XDC file:8 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[25]}]
set_property src_info {type:SCOPED_XDC file:8 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[26]}]
set_property src_info {type:SCOPED_XDC file:8 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[26]}]
set_property src_info {type:SCOPED_XDC file:8 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[27]}]
set_property src_info {type:SCOPED_XDC file:8 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[27]}]
set_property src_info {type:SCOPED_XDC file:8 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[28]}]
set_property src_info {type:SCOPED_XDC file:8 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[28]}]
set_property src_info {type:SCOPED_XDC file:8 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[29]}]
set_property src_info {type:SCOPED_XDC file:8 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[29]}]
set_property src_info {type:SCOPED_XDC file:8 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[2]}]
set_property src_info {type:SCOPED_XDC file:8 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[2]}]
set_property src_info {type:SCOPED_XDC file:8 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[30]}]
set_property src_info {type:SCOPED_XDC file:8 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[30]}]
set_property src_info {type:SCOPED_XDC file:8 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[31]}]
set_property src_info {type:SCOPED_XDC file:8 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[31]}]
set_property src_info {type:SCOPED_XDC file:8 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[32]}]
set_property src_info {type:SCOPED_XDC file:8 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[32]}]
set_property src_info {type:SCOPED_XDC file:8 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[33]}]
set_property src_info {type:SCOPED_XDC file:8 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[33]}]
set_property src_info {type:SCOPED_XDC file:8 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[34]}]
set_property src_info {type:SCOPED_XDC file:8 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[34]}]
set_property src_info {type:SCOPED_XDC file:8 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[35]}]
set_property src_info {type:SCOPED_XDC file:8 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[35]}]
set_property src_info {type:SCOPED_XDC file:8 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[36]}]
set_property src_info {type:SCOPED_XDC file:8 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[36]}]
set_property src_info {type:SCOPED_XDC file:8 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[37]}]
set_property src_info {type:SCOPED_XDC file:8 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[37]}]
set_property src_info {type:SCOPED_XDC file:8 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[38]}]
set_property src_info {type:SCOPED_XDC file:8 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[38]}]
set_property src_info {type:SCOPED_XDC file:8 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[39]}]
set_property src_info {type:SCOPED_XDC file:8 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[39]}]
set_property src_info {type:SCOPED_XDC file:8 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[3]}]
set_property src_info {type:SCOPED_XDC file:8 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[3]}]
set_property src_info {type:SCOPED_XDC file:8 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[40]}]
set_property src_info {type:SCOPED_XDC file:8 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[40]}]
set_property src_info {type:SCOPED_XDC file:8 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[41]}]
set_property src_info {type:SCOPED_XDC file:8 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[41]}]
set_property src_info {type:SCOPED_XDC file:8 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[42]}]
set_property src_info {type:SCOPED_XDC file:8 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[42]}]
set_property src_info {type:SCOPED_XDC file:8 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[43]}]
set_property src_info {type:SCOPED_XDC file:8 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[43]}]
set_property src_info {type:SCOPED_XDC file:8 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[44]}]
set_property src_info {type:SCOPED_XDC file:8 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[44]}]
set_property src_info {type:SCOPED_XDC file:8 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[45]}]
set_property src_info {type:SCOPED_XDC file:8 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[45]}]
set_property src_info {type:SCOPED_XDC file:8 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[46]}]
set_property src_info {type:SCOPED_XDC file:8 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[46]}]
set_property src_info {type:SCOPED_XDC file:8 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[47]}]
set_property src_info {type:SCOPED_XDC file:8 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[47]}]
set_property src_info {type:SCOPED_XDC file:8 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[48]}]
set_property src_info {type:SCOPED_XDC file:8 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[48]}]
set_property src_info {type:SCOPED_XDC file:8 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[49]}]
set_property src_info {type:SCOPED_XDC file:8 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[49]}]
set_property src_info {type:SCOPED_XDC file:8 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[4]}]
set_property src_info {type:SCOPED_XDC file:8 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[4]}]
set_property src_info {type:SCOPED_XDC file:8 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[50]}]
set_property src_info {type:SCOPED_XDC file:8 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[50]}]
set_property src_info {type:SCOPED_XDC file:8 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[51]}]
set_property src_info {type:SCOPED_XDC file:8 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[51]}]
set_property src_info {type:SCOPED_XDC file:8 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[52]}]
set_property src_info {type:SCOPED_XDC file:8 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[52]}]
set_property src_info {type:SCOPED_XDC file:8 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[53]}]
set_property src_info {type:SCOPED_XDC file:8 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[53]}]
set_property src_info {type:SCOPED_XDC file:8 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[54]}]
set_property src_info {type:SCOPED_XDC file:8 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[54]}]
set_property src_info {type:SCOPED_XDC file:8 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[55]}]
set_property src_info {type:SCOPED_XDC file:8 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[55]}]
set_property src_info {type:SCOPED_XDC file:8 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[56]}]
set_property src_info {type:SCOPED_XDC file:8 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[56]}]
set_property src_info {type:SCOPED_XDC file:8 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[57]}]
set_property src_info {type:SCOPED_XDC file:8 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[57]}]
set_property src_info {type:SCOPED_XDC file:8 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[58]}]
set_property src_info {type:SCOPED_XDC file:8 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[58]}]
set_property src_info {type:SCOPED_XDC file:8 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[59]}]
set_property src_info {type:SCOPED_XDC file:8 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[59]}]
set_property src_info {type:SCOPED_XDC file:8 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[5]}]
set_property src_info {type:SCOPED_XDC file:8 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[5]}]
set_property src_info {type:SCOPED_XDC file:8 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[60]}]
set_property src_info {type:SCOPED_XDC file:8 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[60]}]
set_property src_info {type:SCOPED_XDC file:8 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[61]}]
set_property src_info {type:SCOPED_XDC file:8 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[61]}]
set_property src_info {type:SCOPED_XDC file:8 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[62]}]
set_property src_info {type:SCOPED_XDC file:8 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[62]}]
set_property src_info {type:SCOPED_XDC file:8 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[63]}]
set_property src_info {type:SCOPED_XDC file:8 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[63]}]
set_property src_info {type:SCOPED_XDC file:8 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[6]}]
set_property src_info {type:SCOPED_XDC file:8 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[6]}]
set_property src_info {type:SCOPED_XDC file:8 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[7]}]
set_property src_info {type:SCOPED_XDC file:8 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[7]}]
set_property src_info {type:SCOPED_XDC file:8 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[8]}]
set_property src_info {type:SCOPED_XDC file:8 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[8]}]
set_property src_info {type:SCOPED_XDC file:8 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[9]}]
set_property src_info {type:SCOPED_XDC file:8 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dq[9]}]
set_property src_info {type:SCOPED_XDC file:8 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_c[0]}]
set_property src_info {type:SCOPED_XDC file:8 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_c[0]}]
set_property src_info {type:SCOPED_XDC file:8 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_c[1]}]
set_property src_info {type:SCOPED_XDC file:8 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_c[1]}]
set_property src_info {type:SCOPED_XDC file:8 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_c[2]}]
set_property src_info {type:SCOPED_XDC file:8 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_c[2]}]
set_property src_info {type:SCOPED_XDC file:8 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_c[3]}]
set_property src_info {type:SCOPED_XDC file:8 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_c[3]}]
set_property src_info {type:SCOPED_XDC file:8 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_c[4]}]
set_property src_info {type:SCOPED_XDC file:8 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_c[4]}]
set_property src_info {type:SCOPED_XDC file:8 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_c[5]}]
set_property src_info {type:SCOPED_XDC file:8 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_c[5]}]
set_property src_info {type:SCOPED_XDC file:8 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_c[6]}]
set_property src_info {type:SCOPED_XDC file:8 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_c[6]}]
set_property src_info {type:SCOPED_XDC file:8 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_c[7]}]
set_property src_info {type:SCOPED_XDC file:8 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_c[7]}]
set_property src_info {type:SCOPED_XDC file:8 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_t[0]}]
set_property src_info {type:SCOPED_XDC file:8 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_t[0]}]
set_property src_info {type:SCOPED_XDC file:8 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_t[1]}]
set_property src_info {type:SCOPED_XDC file:8 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_t[1]}]
set_property src_info {type:SCOPED_XDC file:8 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_t[2]}]
set_property src_info {type:SCOPED_XDC file:8 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_t[2]}]
set_property src_info {type:SCOPED_XDC file:8 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_t[3]}]
set_property src_info {type:SCOPED_XDC file:8 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_t[3]}]
set_property src_info {type:SCOPED_XDC file:8 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_t[4]}]
set_property src_info {type:SCOPED_XDC file:8 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_t[4]}]
set_property src_info {type:SCOPED_XDC file:8 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_t[5]}]
set_property src_info {type:SCOPED_XDC file:8 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_t[5]}]
set_property src_info {type:SCOPED_XDC file:8 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_t[6]}]
set_property src_info {type:SCOPED_XDC file:8 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_t[6]}]
set_property src_info {type:SCOPED_XDC file:8 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_t[7]}]
set_property src_info {type:SCOPED_XDC file:8 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_dqs_t[7]}]
set_property src_info {type:SCOPED_XDC file:8 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr4_odt[0]}]
set_property src_info {type:SCOPED_XDC file:8 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {c0_ddr4_odt[0]}]
set_property src_info {type:SCOPED_XDC file:8 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports c0_ddr4_reset_n]
set_property src_info {type:SCOPED_XDC file:8 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports c0_ddr4_reset_n]
set_property src_info {type:SCOPED_XDC file:8 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports c0_sys_clk_clk_n]
set_property src_info {type:SCOPED_XDC file:8 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports c0_sys_clk_clk_n]
set_property src_info {type:SCOPED_XDC file:8 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports c0_sys_clk_clk_p]
set_property src_info {type:SCOPED_XDC file:8 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports c0_sys_clk_clk_p]
set_property src_info {type:SCOPED_XDC file:8 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells static_region_i/ddr4_0]
set_property src_info {type:SCOPED_XDC file:9 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 3.333 [get_pins static_region_i/rst_ddr4_0_300M/slowest_sync_clk]
set_property src_info {type:SCOPED_XDC file:9 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells static_region_i/rst_ddr4_0_300M]
set_property src_info {type:SCOPED_XDC file:10 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells static_region_i/util_vector_logic_0]
set_property src_info {type:SCOPED_XDC file:11 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 3.333 [get_pins static_region_i/axi_smc/aclk]
set_property src_info {type:SCOPED_XDC file:11 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 4 [get_pins static_region_i/axi_smc/aclk1]
set_property src_info {type:SCOPED_XDC file:11 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells static_region_i/axi_smc]
set_property src_info {type:SCOPED_XDC file:12 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 3.333 [get_pins static_region_i/xdma_0_axi_periph/s00_couplers/auto_cc/m_axi_aclk]
set_property src_info {type:SCOPED_XDC file:12 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 4 [get_pins static_region_i/xdma_0_axi_periph/s00_couplers/auto_cc/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:12 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells static_region_i/xdma_0_axi_periph/s00_couplers/auto_cc]
set_property src_info {type:SCOPED_XDC file:13 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 3.333 [get_pins static_region_i/pr_region/axi_interconnect_1/s00_couplers/auto_us/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:13 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells static_region_i/pr_region/axi_interconnect_1/s00_couplers/auto_us]
set_property src_info {type:XDC file:15 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [get_ports c0_sys_clk_clk_p]
set_property src_info {type:XDC file:15 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [get_ports c0_sys_clk_clk_n]
set_property src_info {type:XDC file:15 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM_ADV TERM_100 [get_ports c0_sys_clk_clk_p]
set_property src_info {type:XDC file:15 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM_ADV TERM_100 [get_ports c0_sys_clk_clk_n]
set_property src_info {type:XDC file:16 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports reset_rtl]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells static_region_i]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells static_region_i/axi_smc]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells static_region_i/ddr4_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells static_region_i/pr_decoupler_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells static_region_i/pr_region/axi_interconnect_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells static_region_i/pr_region/axi_interconnect_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells static_region_i/pr_region/axi_interconnect_1/s00_couplers/auto_us]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells static_region_i/pr_region/dummy1_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells static_region_i/pr_region/pcl_axifull_bridge_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells static_region_i/pr_region/pcl_axilite_bridge_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells static_region_i/rst_ddr4_0_300M]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells static_region_i/util_ds_buf]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells static_region_i/util_vector_logic_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells static_region_i/xdma_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells static_region_i/xdma_0_axi_periph]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells static_region_i/xdma_0_axi_periph/s00_couplers/auto_cc]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells static_region_i/xdma_0_axi_periph/xbar]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 4.000 -name static_region_i/xdma_0/axi_aclk [get_pins static_region_i/xdma_0/axi_aclk]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name static_region_i/xdma_0/sys_clk [get_pins static_region_i/xdma_0/sys_clk]
set_property src_info {type:SCOPED_XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name static_region_i/xdma_0/sys_clk_gt [get_pins static_region_i/xdma_0/sys_clk_gt]
set_property src_info {type:SCOPED_XDC file:3 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {static_region_i/xdma_0/int_qpll1outclk_out[0]} -source [get_pins static_region_i/xdma_0/sys_clk_gt] -edges {1 2 3} -edge_shift {0.000 -4.900 -9.800} [get_pins {static_region_i/xdma_0/int_qpll1outclk_out[0]}]
set_property src_info {type:SCOPED_XDC file:3 line:5 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {static_region_i/xdma_0/int_qpll1outclk_out[1]} -source [get_pins static_region_i/xdma_0/sys_clk_gt] -edges {1 2 3} -edge_shift {0.000 -4.900 -9.800} [get_pins {static_region_i/xdma_0/int_qpll1outclk_out[1]}]
set_property src_info {type:SCOPED_XDC file:3 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {static_region_i/xdma_0/int_qpll1outrefclk_out[0]} -source [get_pins static_region_i/xdma_0/sys_clk_gt] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_pins {static_region_i/xdma_0/int_qpll1outrefclk_out[0]}]
set_property src_info {type:SCOPED_XDC file:3 line:7 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {static_region_i/xdma_0/int_qpll1outrefclk_out[1]} -source [get_pins static_region_i/xdma_0/sys_clk_gt] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_pins {static_region_i/xdma_0/int_qpll1outrefclk_out[1]}]
set_property src_info {type:SCOPED_XDC file:8 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 3.332 -name c0_sys_clk_clk_p [get_ports c0_sys_clk_clk_p]
set_property src_info {type:SCOPED_XDC file:8 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name static_region_i/ddr4_0/c0_ddr4_ui_clk -source [get_ports c0_sys_clk_clk_p] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_pins static_region_i/ddr4_0/c0_ddr4_ui_clk]
set_property src_info {type:SCOPED_XDC file:8 line:3 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name static_region_i/ddr4_0/dbg_clk -source [get_ports c0_sys_clk_clk_p] -edges {1 2 3} -edge_shift {0.000 4.998 9.996} [get_pins static_region_i/ddr4_0/dbg_clk]
set_property src_info {type:XDC file:16 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_ports reset_rtl]
set_property src_info {type:XDC file:16 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_ports reset_rtl] 100.000
