# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-20700-agent-8/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xcvu095-ffvc1517-2-e

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/savi/8v3shell/mig_shell/mig_shell_proj/mig_shell.srcs/sources_1/bd/static_region/ipshared/bcea/hdl/verilog
    /home/savi/8v3shell/mig_shell/mig_shell_proj/mig_shell.srcs/sources_1/bd/static_region/ipshared/7e3a/hdl
    /home/savi/8v3shell/mig_shell/mig_shell_proj/mig_shell.srcs/sources_1/bd/static_region/ip/static_region_ddr4_0_0/ip_1/rtl/map
    /home/savi/8v3shell/mig_shell/mig_shell_proj/mig_shell.srcs/sources_1/bd/static_region/ip/static_region_ddr4_0_0/rtl/ip_top
    /home/savi/8v3shell/mig_shell/mig_shell_proj/mig_shell.srcs/sources_1/bd/static_region/ip/static_region_ddr4_0_0/rtl/cal
    /home/savi/8v3shell/mig_shell/mig_shell_proj/mig_shell.srcs/sources_1/bd/static_region/ipshared/39ca/hdl/verilog
    /home/savi/8v3shell/mig_shell/mig_shell_proj/mig_shell.srcs/sources_1/bd/static_region/ipshared/f80f/hdl/verilog
  } {
      /opt/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /opt/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      /opt/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    /home/savi/8v3shell/mig_shell/mig_shell_proj/mig_shell.srcs/sources_1/bd/static_region/ipshared/bcea/hdl/verilog
    /home/savi/8v3shell/mig_shell/mig_shell_proj/mig_shell.srcs/sources_1/bd/static_region/ipshared/7e3a/hdl
    /home/savi/8v3shell/mig_shell/mig_shell_proj/mig_shell.srcs/sources_1/bd/static_region/ip/static_region_ddr4_0_0/ip_1/rtl/map
    /home/savi/8v3shell/mig_shell/mig_shell_proj/mig_shell.srcs/sources_1/bd/static_region/ip/static_region_ddr4_0_0/rtl/ip_top
    /home/savi/8v3shell/mig_shell/mig_shell_proj/mig_shell.srcs/sources_1/bd/static_region/ip/static_region_ddr4_0_0/rtl/cal
    /home/savi/8v3shell/mig_shell/mig_shell_proj/mig_shell.srcs/sources_1/bd/static_region/ipshared/39ca/hdl/verilog
    /home/savi/8v3shell/mig_shell/mig_shell_proj/mig_shell.srcs/sources_1/bd/static_region/ipshared/f80f/hdl/verilog
  } {
      ./.Xil/Vivado-20700-agent-8/realtime/static_region_pr_decoupler_0_0_stub.v
      ./.Xil/Vivado-20700-agent-8/realtime/static_region_util_ds_buf_0_stub.v
      ./.Xil/Vivado-20700-agent-8/realtime/static_region_xdma_0_0_stub.v
      ./.Xil/Vivado-20700-agent-8/realtime/static_region_xbar_0_stub.v
      ./.Xil/Vivado-20700-agent-8/realtime/static_region_dummy1_0_0_stub.v
      ./.Xil/Vivado-20700-agent-8/realtime/static_region_pcl_axifull_bridge_0_0_stub.v
      ./.Xil/Vivado-20700-agent-8/realtime/static_region_pcl_axilite_bridge_0_0_stub.v
      ./.Xil/Vivado-20700-agent-8/realtime/static_region_ddr4_0_0_stub.v
      ./.Xil/Vivado-20700-agent-8/realtime/static_region_rst_ddr4_0_300M_0_stub.v
      ./.Xil/Vivado-20700-agent-8/realtime/static_region_util_vector_logic_0_0_stub.v
      ./.Xil/Vivado-20700-agent-8/realtime/static_region_axi_smc_1_stub.v
      ./.Xil/Vivado-20700-agent-8/realtime/static_region_auto_cc_0_stub.v
      ./.Xil/Vivado-20700-agent-8/realtime/static_region_auto_us_0_stub.v
      /home/savi/8v3shell/mig_shell/mig_shell_proj/mig_shell.srcs/sources_1/bd/static_region/hdl/static_region.v
      /home/savi/8v3shell/mig_shell/mig_shell_proj/mig_shell.srcs/sources_1/bd/static_region/hdl/static_region_wrapper.v
    }
      rt::read_vhdl -lib xpm /opt/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-20700-agent-8/realtime/static_region_wrapper_synth.xdc
    rt::sdcChecksum
    set rt::top static_region_wrapper
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {/home/savi/8v3shell/mig_shell/mig_shell_proj/mig_shell.cache/wt}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-20700-agent-8/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
