set_property SRC_FILE_INFO {cfile:/home/savi/8v3shell/mig_shell/.Xil/Vivado-30308-agent-8/dcp17/pr_region_2_fc_layer_0_0_in_context.xdc rfile:../dcp17/pr_region_2_fc_layer_0_0_in_context.xdc id:1 order:EARLY scoped_inst:pr_region_2_i/fc_layer_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/savi/8v3shell/mig_shell/.Xil/Vivado-30308-agent-8/dcp19/pr_region_2_conv_layer_0_0_in_context.xdc rfile:../dcp19/pr_region_2_conv_layer_0_0_in_context.xdc id:2 order:EARLY scoped_inst:pr_region_2_i/conv_layer_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/savi/8v3shell/mig_shell/.Xil/Vivado-30308-agent-8/dcp21/pr_region_2_pcl_axifull_bridge_0_0_in_context.xdc rfile:../dcp21/pr_region_2_pcl_axifull_bridge_0_0_in_context.xdc id:3 order:EARLY scoped_inst:pr_region_2_i/pcl_axifull_bridge_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/savi/8v3shell/mig_shell/.Xil/Vivado-30308-agent-8/dcp23/pr_region_2_pcl_axilite_bridge_0_0_in_context.xdc rfile:../dcp23/pr_region_2_pcl_axilite_bridge_0_0_in_context.xdc id:4 order:EARLY scoped_inst:pr_region_2_i/pcl_axilite_bridge_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/savi/8v3shell/mig_shell/.Xil/Vivado-30308-agent-8/dcp25/pr_region_2_xbar_1_in_context.xdc rfile:../dcp25/pr_region_2_xbar_1_in_context.xdc id:5 order:EARLY scoped_inst:pr_region_2_i/axi_interconnect_1/xbar} [current_design]
set_property SRC_FILE_INFO {cfile:/home/savi/8v3shell/mig_shell/.Xil/Vivado-30308-agent-8/dcp27/pr_region_2_xbar_0_in_context.xdc rfile:../dcp27/pr_region_2_xbar_0_in_context.xdc id:6 order:EARLY scoped_inst:pr_region_2_i/axi_interconnect_0/xbar} [current_design]
set_property SRC_FILE_INFO {cfile:/home/savi/8v3shell/mig_shell/.Xil/Vivado-30308-agent-8/dcp29/pr_region_2_auto_us_1_in_context.xdc rfile:../dcp29/pr_region_2_auto_us_1_in_context.xdc id:7 order:EARLY scoped_inst:pr_region_2_i/axi_interconnect_1/s01_couplers/auto_us} [current_design]
set_property SRC_FILE_INFO {cfile:/home/savi/8v3shell/mig_shell/.Xil/Vivado-30308-agent-8/dcp31/pr_region_2_auto_us_0_in_context.xdc rfile:../dcp31/pr_region_2_auto_us_0_in_context.xdc id:8 order:EARLY scoped_inst:pr_region_2_i/axi_interconnect_1/s00_couplers/auto_us} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 3.333 [get_pins pr_region_2_i/fc_layer_0/ap_clk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells pr_region_2_i/fc_layer_0]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 3.333 [get_pins pr_region_2_i/conv_layer_0/ap_clk]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells pr_region_2_i/conv_layer_0]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells pr_region_2_i/pcl_axifull_bridge_0]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells pr_region_2_i/pcl_axilite_bridge_0]
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 4 [get_pins pr_region_2_i/axi_interconnect_1/xbar/aclk]
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells pr_region_2_i/axi_interconnect_1/xbar]
set_property src_info {type:SCOPED_XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 4 [get_pins pr_region_2_i/axi_interconnect_0/xbar/aclk]
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells pr_region_2_i/axi_interconnect_0/xbar]
set_property src_info {type:SCOPED_XDC file:7 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 4 [get_pins pr_region_2_i/axi_interconnect_1/s01_couplers/auto_us/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:7 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells pr_region_2_i/axi_interconnect_1/s01_couplers/auto_us]
set_property src_info {type:SCOPED_XDC file:8 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 4 [get_pins pr_region_2_i/axi_interconnect_1/s00_couplers/auto_us/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:8 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells pr_region_2_i/axi_interconnect_1/s00_couplers/auto_us]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells pr_region_2_i]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells pr_region_2_i/axi_interconnect_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells pr_region_2_i/axi_interconnect_0/xbar]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells pr_region_2_i/axi_interconnect_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells pr_region_2_i/axi_interconnect_1/s00_couplers/auto_us]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells pr_region_2_i/axi_interconnect_1/s01_couplers/auto_us]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells pr_region_2_i/axi_interconnect_1/xbar]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells pr_region_2_i/conv_layer_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells pr_region_2_i/fc_layer_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells pr_region_2_i/pcl_axifull_bridge_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells pr_region_2_i/pcl_axilite_bridge_0]
